version: 1
policy:
  pullRequests: public
tasks:
  - taskId: {$eval: as_slugid("py2-image")}
    created: {$fromNow: ""}
    deadline: {$fromNow: "1 hour"}
    provisionerId: aws-provisioner-v1
    workerType: github-worker
    payload:
      maxRunTime: 1200
      image: "taskcluster/image_builder:0.1.5"
      features:
        dind: true
      command:
        - "/bin/bash"
        - "-c"
        - "git clone ${event.pull_request.head.repo.clone_url} balrog && cd balrog && git checkout ${event.pull_request.head.ref} && docker build -t balrogtest -f Dockerfile.dev . && docker save -o /balrogtest.tar balrogtest"
      artifacts:
        public/balrogtest.tar:
          path: /balrogtest.tar
          type: file
    metadata:
      name: "Build test runner image"
      description: "Build test runner image"
      owner: ${event.sender.login}@users.noreply.github.com
      source: ${event.repository.url}
  - taskId: {$eval: as_slugid("py2-tests")}
    dependencies:
      - {$eval: as_slugid("py2-image")}
    created: {$fromNow: ""}
    deadline: {$fromNow: "1 hour"}
    provisionerId: aws-provisioner-v1
    workerType: github-worker
    payload:
      maxRunTime: 1200
      image:
        path: "public/balrogtest.tar"
        type: "task-image"
        taskId: {$eval: as_slugid("py2-image")}
      command:
        - "/bin/bash"
        - "-c"
        - "git clone ${event.pull_request.head.repo.clone_url} balrog && cd balrog && git checkout ${event.pull_request.head.ref} && tox -e py27"
    metadata:
      name: "Run python2 tests"
      description: "Run python2 tests"
      owner: ${event.sender.login}@users.noreply.github.com
      source: ${event.repository.url}
